### ISSUE TITLE
Задание 2. Добавить README

### ISSUE THREAD

**Issue by timk01** [gpb-it-factory/khasmamedov-telergam-bot#3]
В созданный нами репозиторий в ходе [первого задания](https://github.com/gpb-it-factory/practice/blob/trunk/exercises/1_create_repository) добавляем в корне файл README.md, описываем там информацию о репозитории (что будет озвучено в рамках [лекции](https://github.com/gpb-it-factory/curriculum/tree/trunk/lectures/6_readme)). Да, мы пока не знаем некоторых деталей проекта, но знаем зачем нужен будет этот компонент. Добавьте туда всё, что считаете необходимым. Главная цель - попрактиковать Markdown и понять для чего вообще нужен README.

**Comment by vaganov-vadim** [comment]
Ветка должна называться feature/3 - номер тикета - 3.

**Comment by timk01** [comment]
Я верно понял, что с условием отсутствия issue#3, у меня и название **первой** ветки будет теперь feature/2 ?
